# List of major Indian cities
INDIAN_CITIES = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata",
    "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur",
    "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad",
    "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik",
    "Faridabad", "Meerut", "Rajkot", "Varanasi", "Srinagar", "Amritsar",
    "Navi Mumbai", "Allahabad", "Howrah", "Ranchi", "Gwalior", "Jabalpur",
    "Coimbatore", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota",
    "Guwahati", "Chandigarh", "Solapur", "Hubli-Dharwad", "Bareilly", "Mysore",
    "Moradabad", "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar",
    "Salem", "Warangal", "Guntur", "Bhiwandi", "Saharanpur", "Gorakhpur",
    "Bikaner", "Amravati", "Noida", "Jamshedpur", "Bhilai", "Cuttack",
    "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun", "Durgapur",
    "Asansol", "Rourkela", "Nanded", "Kolhapur", "Ajmer", "Akola",
    "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi",
    "Ulhasnagar", "Jammu", "Sangli-Miraj", "Mangalore", "Erode", "Belgaum",
    "Ambattur", "Tirunelveli", "Malegaon", "Gaya", "Jalgaon", "Udaipur",
    "Maheshtala", "Tirupur", "Davanagere", "Kozhikode", "Kurnool", "Rajahmundry",
    "Bokaro", "South Dumdum", "Bellary", "Patiala", "Gopalpur", "Agartala",
    "Bhagalpur", "Muzaffarnagar", "Bhatpara", "Panihati", "Latur", "Dhule",
    "Rohtak", "Korba", "Bhilwara", "Berhampur", "Muzaffarpur", "Ahmednagar",
    "Mathura", "Kollam", "Avadi", "Kadapa", "Kamarhati", "Sambalpur",
    "Bilaspur", "Shahjahanpur", "Satara", "Bijapur", "Rampur", "Shivamogga",
    "Chandrapur", "Junagadh", "Thrissur", "Alwar", "Bardhaman", "Kulti",
    "Nizamabad", "Parbhani", "Tumkur", "Khammam", "Ozhukarai", "Bihar Sharif",
    "Panipat", "Darbhanga", "Bally", "Aizawl", "Dewas", "Ichalkaranji",
    "Karnal", "Bathinda", "Jalna", "Eluru", "Barasat", "Kirari Suleman Nagar",
    "Purnia", "Katihar", "Navi Mumbai-Panvel", "Sangrur", "Bulandshahr", "Munger",
    "Panchkula", "Burhanpur", "Khandwa", "Morena", "Raebareli", "Bhiwani",
    "Bharatpur", "Hapur", "Barmer", "Dhanbad", "Bhind", "Chittorgarh",
    "Haldia", "Habra", "Ongole", "Nadiad", "Chhapra", "Hajipur",
    "Sikar", "Port Blair", "Karaikudi", "Mirzapur", "Fatehpur", "Raiganj",
    "Bhusawal", "Bidar", "Gangtok", "Dharmavaram", "Medininagar", "Gandhinagar",
    "Baranagar", "Tinsukia", "Balurghat", "Nagaon", "Lakhimpur", "Sitapur",
    "Hoshiarpur", "Ambala", "Hardwar", "Rishikesh", "Kashipur", "Roorkee",
    "Rudrapur", "Haldwani", "Nainital", "Almora", "Pithoragarh", "Chamoli",
    "Pauri", "Tehri", "Uttarkashi", "Champawat", "Bageshwar", "Alappuzha", "Anand", "Anantapur", "Aurangabad", "Baddi", "Baddi", 
    "Bahadurgarh", "Ballabhgarh", "Bardhaman", "Bareilly", "Bathinda",
    "Bettiah", "Bharatpur", "Bhiwadi", "Bidar", "Bilaspur", "Bongaigaon",
    "Budaun", "Chandausi", "Chandigarh", "Chhindwara", "Chitradurga",
    "Chittoor", "Cooch Behar", "Cuddalore", "Dabhoi", "Dahod", "Daman",
    "Darbhanga", "Darjeeling", "Dharamshala", "Dharwad", "Dholpur",
    "Dibrugarh", "Dimapur", "Dindigul", "Diu", "Dombivli", "Dumka",
    "Etah", "Etawah", "Faizabad", "Faridkot", "Farrukhabad", "Fatehabad",
    "Firozpur", "Gadag", "Gandhidham", "Gangapur", "Ganjam", "Ghazipur",
    "Giridih", "Godhra", "Gokak", "Gonda", "Gondia", "Gopalganj",
    "Gudivada", "Guna", "Guntakal", "Gurdaspur", "Hajipur", "Hamirpur",
    "Hanumangarh", "Hardoi", "Hassan", "Hathras", "Hazaribagh", "Hisar",
    "Hoshangabad", "Hospet", "Hubli", "Imphal", "Itanagar", "Jagdalpur",
    "Jagraon", "Jagtial", "Jalpaiguri", "Jamalpur", "Jamui", "Jangaon",
    "Jatani", "Jhalawar", "Jhargram", "Jhunjhunu", "Jind", "Jorhat",
    "Kadiri", "Kaithal", "Kakinada", "Kalaburagi", "Kalimpong", "Kalpetta",
    "Kalyani", "Kamareddy", "Kancheepuram", "Kandla", "Kangra", "Kannauj",
    "Kapurthala", "Karaikal", "Karimnagar", "Karur", "Karwar", "Kasganj",
    "Kasaragod", "Kathua", "Katni", "Kavali", "Kayamkulam", "Kendujhar",
    "Keshod", "Khagaria", "Khanna", "Kharagpur", "Khargone", "Khatima",
    "Kheda", "Kheri", "Khurda", "Kishanganj", "Kishangarh", "Kodagu",
    "Kodungallur", "Kohima", "Kolar", "Koppal", "Koraput", "Kotdwara",
    "Kothagudem", "Kottakkal", "Kottayam", "Kovilpatti", "Krishnagiri",
    "Krishnanagar", "Kullu", "Kumbakonam", "Kumta", "Kundapura",
    "Kurukshetra", "Kushinagar", "Lalitpur", "Laxmangarh", "Leh",
    "Lohardaga", "Machilipatnam", "Madanapalle", "Madhubani", "Madikeri",
    "Mahbubnagar", "Mahesana", "Mahoba", "Mainpuri", "Malda", "Malkapur",
    "Mancherial", "Mandla", "Mandsaur", "Mandya", "Mangalagiri", "Mangrol",
    "Manjeri", "Mannargudi", "Manor", "Mansa", "Margao", "Mattancherry",
    "Mehsana", "Mettur", "Mhow", "Miryalaguda", "Modinagar", "Moga",
    "Mohali", "Morvi", "Motihari", "Muktsar", "Murshidabad", "Nabadwip",
    "Nalanda", "Nalgonda", "Nandurbar", "Nandyal", "Nangal", "Narasaraopet",
    "Narayanpet", "Narnaul", "Narsinghpur", "Nathdwara", "Navsari",
    "Nawada", "Nawanshahr", "Nawashahr", "Nayagarh", "Neemuch", "Neyveli",
    "Nongpoh", "Nongstoin", "North Lakhimpur", "Nowgong", "Orai",
    "Osmanabad", "Ottapalam", "Pachmarhi", "Padrauna", "Palanpur",
    "Palayankottai", "Palghar", "Pali", "Palitana", "Palladam",
    "Pallavaram", "Palwal", "Panaji", "Pandharpur", "Peddapuram",
    "Perambalur", "Perinthalmanna", "Phagwara", "Phulbani", "Pilibhit",
    "Pithampur", "Pollachi", "Pondicherry", "Porbandar", "Pratapgarh",
    "Proddatur", "Pudukkottai", "Pulwama", "Puri", "Purulia", "Pusa",
    "Pushkar", "Raichur", "Raigarh", "Rajapalayam", "Rajgarh",
    "Rajnandgaon", "Rajsamand", "Ramanathapuram", "Ranaghat", "Ranikhet",
    "Rasipuram", "Ratlam", "Ratnagiri", "Rewa", "Rewari", "Robertsganj",
    "Ropar", "Sagar", "Saharsa", "Sahibganj", "Saidapur", "Samastipur",
    "Sambhal", "Sangli", "Santipur", "Saran", "Sasaram", "Satna",
    "Sawai Madhopur", "Sehore", "Seoni", "Shahdol", "Shajapur", "Shamli",
    "Sheikhpura", "Sheopur", "Shillong", "Shimla", "Shimoga", "Shivpuri",
    "Sholapur", "Siddharthnagar", "Silchar", "Sindhudurg", "Singrauli",
    "Sirohi", "Sirsa", "Sitamarhi", "Solan", "Sonipat", "Sopore",
    "Srikakulam", "Srirangam", "Srivilliputhur", "Sultanpur", "Sundargarh",
    "Surendranagar", "Suryapet", "Tadepalligudem", "Tadpatri",
    "Talegaon Dabhade", "Tamluk", "Tandur", "Tanuku", "Tarakeswar",
    "Tarn Taran", "Tenali", "Tezpur", "Thalassery", "Thanjavur", "Theni",
    "Thiruvalla", "Thiruvananthapuram", "Thiruvarur", "Thodupuzha",
    "Thoothukudi", "Tikamgarh", "Tirupati", "Tiruvannamalai", "Titagarh",
    "Tonk", "Tuni", "Udgir", "Udhampur", "Udupi", "Umred", "Una",
    "Unnao", "Uppal", "Uran", "Vaduz", "Vaishali", "Valsad", "Vaniyambadi",
    "Vapi", "Varkala", "Vasai-Virar", "Vellore", "Veraval", "Vidisha",
    "Vikarabad", "Villupuram", "Vinukonda", "Virudhunagar", "Vizianagaram",
    "Wardha", "Washim", "Wayanad", "Yamunanagar", "Yavatmal", "Yemmiganur",
    "Yercaud", "Zirakpur", "Zunheboto"
]

def get_cities():
    """Return sorted list of unique cities"""
    # Remove duplicates while preserving order, then sort
    seen = set()
    unique_cities = []
    for city in INDIAN_CITIES:
        if city not in seen:
            seen.add(city)
            unique_cities.append(city)
    return sorted(unique_cities)

